services:

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8080:2368
    environment:

      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: GH0ST
      database__connection__database: ghost
    volumes:
      - ghost:/var/lib/ghost
    networks:
      - public
      - private
    depends_on:
      - db


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: GH0ST
    volumes:
      - db:/var/lib/mysql
    networks:
      - private
    

volumes:
  ghost:
  db:

networks:
  public:
  private:
  